/*
    @Input: Forouzan
    @Expected output as:

    -------------------Senders Side------------------------------

Enter the String data you wanna send:	Forouzan

466f
726f
757a
616e
The Sum generated is 8fc7
The checksum generated is 7038
----------------------------------------------------------------------

Enter 1 if you wanna intoduce an error otherwise press 0:	0

-------------------------------Receiver's side-------------------------

466f
726f
757a
616e
7038
The Sum generated is ffff
The checksum generated is 0
 No error detected
----------------------------------------------------------------------

 */

#include<stdio.h>
#include<string.h>
#include<time.h>

#include<stdlib.h>

char str[100];
int generateChecksum(int mode,int checksum){

    //n is simply for the even length (we wanna take) as we are splitting the word into 2byte words each.
    int n,temp,sum=0;

    //If odd, we add 1 and divide by 2 for converting to even otherwise simply didvide by 2.
    if(strlen(str)%2 != 0){
        n = (strlen(str)+1)/2;
    }
    else{
        n = strlen(str)/2;
    }

    //Now, the function below is the heart of the entire question.
    /*
        Consider the string is Forouzan
        What it does is, at every run it takes two characters, as visible i*2 and i*2+1
        Fo : First it gets the corresponsing decimal value for F and stores in temp.
             Now, an important thing, why in next step while adding value of o we multiply initial value by 256.
             This is because as we are converting the 8 bit data to 16 bit. We need to shift it 8 bits to the right.
             And 2^8 = 256./ So, to shift the word 8 bits and make sure we get 16bit words, we multiply it by 256.
             Once, this is done, we simply add it to the sum

        ro: Same repreated for this.
        uz: Same repeated for this
        an: Same repeated for this
    
     */
    /*
        More detailed answer as to why we multiply by 256, can be found here.
        https://forum.dexterindustries.com/t/why-do-you-need-to-multiply-by-256-and-add-some-bits-when-reading-analog/4538/2
    */
    for(int i=0;i<n;i++){
        temp = str[i*2];
        temp = (temp*256) + str[(i*2)+1];
        printf("\n%x",temp);
        sum = sum+temp;
    }

    //The below code is executed only if the mode bit is 1. That is we are executing code on the receivers side.
    //We need to add the checksum sent by the sender right.
    if(mode == 1){
        printf("\n%x",checksum);
        sum += checksum;
    }
    //Now, even this code is interesting. As sometimes we might have some carry while adding, so we get to know that if 
    // doing the module doesn't come out to be zero. If it comes as zero, we simply do the complement and send.

    //But when, we encounter a carry, the module doesn't come out to be zero and hence we do the steps as usual to add 
    //the carry and so on..
    if(sum%65536 != 0){
        n = sum%65536;
        sum = (sum/65536) + n;
    }
    printf("\nThe Sum generated is %x",sum); // This will be the checksum we obtained.
    sum = 65535 - sum; //Now, as we now we perform the complement. So, subtracting from FFFF in case of hexadecimal
                        // is same as subtracting from 65535 in case of decimal.
    printf("\nThe checksum generated is %x",sum); //This will print the checksum. FInal checksum.

    return sum;
}

void main(){

    int sum1 = 0; //We will use this to store the checksum at the senders side.
    int sum2 = 0; //We will use this to store the checksum at the senders side.

    printf("\n-------------------Senders Side------------------------------\n");
    printf("\nEnter the String data you wanna send:\t");
    scanf("%s",str); //This will be the dataword we wanna send.


    /*
        * Signature of generateChecksum function.
        * generateChecksum(int mode, int checksum)
        * 
        * mode: This basically tells that we are performing the checksum for the receivers side or the senders side.
        *       If mode is 0, hum sender side ke liye kar rhe hai, warna receiver side ke liye.
        * 
        * checksum: This is used for receivers side, when we wanna send the checksum generated by the sender. 
        *           This can be simply put to zero in case of sender.
     */

    sum1 = generateChecksum(0,0); //This will generate the checksum for the particular string and put it in sum1.

    printf("\n----------------------------------------------------------------------\n");
    int ch;
    /*
        * Now, we will ask the user, if he wanna introduce some error. If 1 is pressed, we will randomly change the dataword
        * If he presses 0, we will send the same.
     */

    printf("\nEnter 1 if you wanna intoduce an error otherwise press 0:\t");
    scanf("%d",&ch);    
    srand(time(NULL)); //Why do we do this ? 

    /*
        Here's a reason: time() only changes once per second. If you seed from time(), for each call to rand(),
         then you will get the same value for every call during a single second.
         So, to make sure a different value is generated each time, we use the srand function.
     */
    printf("\n-------------------------------Receiver's side-------------------------\n");
    if(ch == 1){

        //We can modify the dataword itself
        int num = (rand() % (strlen(str)));   //We randomlt generate the index number of the bit to change.
        printf("\nRandom number: %d, so we will change the this indexed character.",num);
        str[num] = 'o'; //We modify the character at that index to 'o'
        sum2 = generateChecksum(1,sum1); //We again generate the checksum.

        /*
            If after tampering, we get the checksum as 0, it means no error occured and if the checksum is not zero,
            it implies that the error occured.
         */

        if(sum2 == 0){
            //As sum is 0, so no error detected.
            printf("\n No error detected");
        }
        else{
            //Error detected here.
            printf("\n Error detected");
        }

    }
    else{
        sum2 = generateChecksum(1,sum1); //We will send the checksum generated and the mode bit here.
        //Again, with the same logic , we will print whether error is detected or not.
        if(sum2 == 0){
            printf("\n No error detected");
        }
        else{
            printf("\n Error detected");
        }
    }

    printf("\n----------------------------------------------------------------------\n");
}

